// Este arquivo só é usado no servidor, pra testes.
// Podemos importar dependências de desenvolvimento.
// Talvez não funcione num ambiente de Integração Contínua (CI).
/* eslint import/no-extraneous-dependencies: ["error", {"devDependencies": true}] */
import React from 'react';
import PropTypes from 'prop-types';
import { addMockFunctionsToSchema } from 'graphql-tools';
import ApolloClient from 'apollo-client';
import { SchemaLink } from 'apollo-link-schema';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { ApolloProvider } from 'react-apollo';
import { globalMocks, schema } from './test-utils';
import mergeResolvers from './mergeResolvers';

// globalMocks uses fake data generated by faker.js
// It is merged with customResolvers, which can be used to customize the data
// returned by specific fields.
const FakeDataProvider = props => {
  const { children, customResolvers = {} } = props;
  const mocks = mergeResolvers(globalMocks, customResolvers);
  addMockFunctionsToSchema({ schema, mocks });

  const client = new ApolloClient({
    link: new SchemaLink({ schema }),
    cache: new InMemoryCache(),
  });

  return <ApolloProvider client={client}>{children}</ApolloProvider>;
};

FakeDataProvider.propTypes = {
  /**
   * Used to render any component that uses a <Query/> or <Mutation/>
   * from 'react-apollo'.
   * The component is wrapped by <ApolloProvider/>, with a mocked ApolloClient.
   */
  children: PropTypes.node.isRequired,
  /**
   * An object with resolvers to be merged with the fake data resolvers.
   * It can be used to override fake data of specific fields:
   * customResolvers = {
   *   Question: () => ({
   *     wording: 'Maria comprou três maças...',
   *     secondaryWording: null,
   *     imageFullUrl: 'http://host.test/image.jpg',
   *     choices: [{ text: '5 maças' }, { text: '3 maças' }],
   *   }),
   * }
   */
  customResolvers: PropTypes.object,
};

export default FakeDataProvider;
