version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/src:/olimat/app/src
    ports:
      - 9000:3000
    links:
      - api
    environment:
      - NODE_ENV=development
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/src:/olimat/api/src
    ports:
      - 9001:8080
    links:
      - db
      - redis
    environment:
      - NODE_ENV=development
      - POSTGRES_PASSWORD=dev12345
  db:
    image: postgres:9.6.4-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dev12345
  redis:
    image: redis:4.0.1-alpine

volumes:
  dbdata:
