version: '3.2'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    environment:
      - NODE_ENV=development
    networks:
      - frontend
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./app/src
        target: /olimat/app/src
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: npm run dev
    depends_on:
      - db
    environment:
      - NODE_ENV=development
    networks:
      - frontend
      - backend
    ports:
      - 3001:3030
    volumes:
      - type: bind
        source: ./api/src
        target: /olimat/api/src
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev123
    networks:
      - backend
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true

networks:
  frontend:
  backend:

volumes:
  db-data:
