version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/usr/src/frontend/src
    ports:
      - 9000:3000
    links:
      - backend
    environment:
      - NODE_ENV=development
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/usr/src/backend/src
    ports:
      - 9001:8080
    links:
      - db
      - redis
    environment:
      - NODE_ENV=development
      - POSTGRES_PASSWORD=dev12345
  db:
    image: postgres:9.6.4-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dev12345
  redis:
    image: redis:4.0.1-alpine

volumes:
  dbdata:
