version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    env_file:
      - .env/app.dev
    networks:
      - frontend
    ports:
      - 3000:3000
    volumes:
      - ./app/src:/olimat/app/src
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - db
      - redis
    env_file:
      - .env/api.dev
      - .env/db.dev
    networks:
      - frontend
      - backend
    ports:
      - 3001:3001
    volumes:
      - ./api/src:/olimat/api/src
  db:
    env_file:
      - .env/db.dev
    image: postgres:9.6.4-alpine
    networks:
      - backend
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:4.0.1-alpine
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  dbdata:
