projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  prisma:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: prisma/prisma.yml
      # Não funciona com a versão 14.0 do 'graphql'
      # codegen:
      # - generator: prisma-binding
      #   language: typescript
      #   output:
      #     binding: src/generated/prisma.ts
