# Parece que a extensão prisma.vscode-graphql usa este arquivo
projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  # O 'graphql-cli' usava essa configuração para os comandos
  # 'graphql get-schema' e 'graphql codegen'
  # prisma:
  #   schemaPath: "src/__generated__/prisma.graphql"
  #   extensions:
  #     prisma: prisma/prisma.yml
      # Não funciona com a versão 14.0 do 'graphql'
      # codegen:
      # - generator: prisma-binding
      #   language: typescript
      #   output:
      #     binding: src/__generated__/prisma.ts
