version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10.15
      - image: postgres:10.5
        environment:
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
      - image: prismagraphql/prisma:1.23
        environment:
          PRISMA_CONFIG: |
            port: 4466
            databases:
              default:
                connector: postgres
                host: localhost
                port: 5432
                user: prisma
                password: prisma
                migrations: true
    working_directory: ~/olimat

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - monorepo-modules-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - monorepo-modules-
      - restore_cache:
          keys:
          - api-modules-{{ checksum "api/package.json" }}
          - api-modules-
      - restore_cache:
          keys:
          - web-modules-{{ checksum "web/package.json" }}
          - web-modules-

      # Install monorepo dependencies
      - run: npm ci
      # Install 'api' and 'web' dependencies
      - run: npx lerna bootstrap --ci
      - run:
          name: Start Prisma server
          command: cd api && npx prisma deploy

      - save_cache:
          paths:
            - node_modules
          key: monorepo-modules-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - api/node_modules
          key: api-modules-{{ checksum "api/package.json" }}
      - save_cache:
          paths:
            - web/node_modules
          key: web-modules-{{ checksum "web/package.json" }}
        
      # run tests!
      - run: npx lerna run test
