FROM node:8.7.0-alpine

WORKDIR /olimat/api

COPY package.json package-lock.json ./

RUN npm install --quiet

COPY ./public ./public
COPY ./config ./config

COPY ./src ./src

COPY ./db ./db
COPY ./bin ./bin
