version: '3.2'

services:
  sut:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: npm test
    depends_on:
      - api
    environment:
      NODE_ENV: test
  api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: npm start
    depends_on:
      - db
    environment:
      NODE_ENV: test
    ports:
      - 3030
    volumes:
      - type: bind
        source: ./src
        target: /olimat/api/src
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev123
    image: postgres:9.6.4-alpine
