FROM node:8.4.0
MAINTAINER Josias Iquabius <iquabius@gmail.com>

WORKDIR /olimat/api

COPY package.json package-lock.json ./

RUN npm install

COPY ./www ./www

COPY ./src ./src

COPY ./knexfile.js ./knexfile.js
COPY ./db ./db

CMD npm start
